language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: target/release/clipboard2json.sh
  skip_cleanup: true
dd:
  secure: DwX3wtHwsYrNtz/PYem34AOq1WvIHBrpHIjaaZMfYsxk6sByJnHHeyJW0AX1dvTRE3jNhxm5mhPCpSAlwzz8ens1k8wmZv12buR2tcEdC/ed1LK/q8cYLbQOe6GtiUzwiIB6CxhGp05vUqAKGcp/EenQOpqs3o7o5RA5drKSD1t7cByYN1niX0E69Dj5cbO3GYmKS4+mk3gQGO2rKT9FnQaPI0zNTULyUxOA2R9v83SDbN2wsCvv34230ugsZtEpDwltiJnp2uFzmVPYm3FkfrbdESS0P28ApBuFAAWb2i6ZQUj1CTCcvrbOP+0Ntt5E7i67J+9CkPbA5eHodMeXx98/De0I8i0cYnezPD67HOcP/N+HoSRm5mp1BtH9L3tCB+8YCbMCgLTCRUUVeIC2CHXuZ9ttGyGqm9Ce8cy+X4HMhyLjALzhCJ4lBbS/qjURfPUaRt2uyTmfmuzjFsNumzu1n/QRYWiXdHzOr8ZCwkYsLAGY2j3zwH3P7+Fr75Gro/vsKJEB2LHZwpwXyXgL+cSHROfCys6YCcZvkeD6rQLrGyLek1b6o6f8DjYxIN2shcwL7V8osboTpWcfE081Couu5LuwLUf5UGbzalXlMUR7r4BIWn46j7WiQN2ndnEClM169XGBv27KbTJMX+hHgKgfO00f668i7DCoiYykYZE=
