language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
jobs:
  include:
    -stage: compile linux assets and publish
    os: linux
    deploy:
      provider: releases
      api_key: $GITHUB_TOKEN
      file: target/release/clipboard2json
      skip_cleanup: true
  include:
    -stage: compile windows assets and publish
    os: windows
    deploy:
      provider: releases
      api_key: $GITHUB_TOKEN
      file: target/release/clipboard2json.exe
      skip_cleanup: true